### PR TITLE
Add oauthenticator 15.1.0

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/jupyterhub/oauthenticator/blob/15.1.0/docs/source/changelog.md
License: https://github.com/jupyterhub/oauthenticator/blob/15.1.0/LICENSE
Requirements: https://github.com/jupyterhub/oauthenticator/blob/15.1.0/setup.py

Actions:
1. Remove noarch python
2. Skip py<36
3. Fix python in host and run
4. Add missing packages to host and run
5. Add pip check
6. Add license_url
7. Add doc_source_url

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
An error on `s390x`:
```
conda.exceptions.ResolvePackageNotFound:
  - ruamel.yaml
```

The package `ruamel` is missing on `s390x` too:
```
conda.exceptions.ResolvePackageNotFound:
  - ruamel
```

**Comment by skupr-anaconda** [comment]
We need to rebuild `ruamel.yaml v0.16.12` https://github.com/AnacondaRecipes/ruamel.yaml-feedstock/pull/10

**Comment by skupr-anaconda** [comment]
ruamel.yaml v0.16.12 was rebuilt

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
